---
- name: copy over the nginx configuration
  template:
    src: etc/nginx/sites-available/hypothesis.conf
    dest: /etc/nginx/sites-available/hypothesis.conf
  tags: nginx-copy

- name: enable the site
  file:
    src: /etc/nginx/sites-available/hypothesis.conf
    dest: /etc/nginx/sites-enabled/hypothesis.conf
    state: link
    force: yes
  notify: restart nginx
